### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by jdumas** [Philip-Trettner/probabilistic-quadrics#1]
Hi there,

Thanks for putting your code online! Would you mind sharing the id of the models you used from Thingi10K? The paper only refers to Thingi10K without specifying exactly which model are used...

Thanks.

**Comment by Philip-Trettner** [comment]
Hi! That's a good point, somehow I missed that:

Anvil: https://ten-thousand-models.appspot.com/detail.html?file_id=91408
Centrifuge: https://ten-thousand-models.appspot.com/detail.html?file_id=734278
Jacket: https://ten-thousand-models.appspot.com/detail.html?file_id=763718

**Comment by jdumas** [comment]
Awesome, thanks!
